name: Publish Airship Package

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: GCP Project
        type: environment
        default: platform-staging
        required: true

jobs:
  publish-npm:
    environment: ${{ inputs.environment || 'platform-production' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm --no-git-tag-version version "$(cat package.json | grep '"version":' | sed -E 's/.*"version": "([0-9]+\.[0-9]+\.)[0-9]+".*/\1/')${{github.run_number}}"
          npm publish --tag ${{vars.NPM_TAG}}
       
